import React, { useState } from "react";
import { Palette, Save, Type, CheckCircle } from "lucide-react";
import { UserProfile, Repo } from "../../types/index";
import { commitFile } from "../../services/githubApi";

interface ThemeOptimizerProps {
  profile: UserProfile;
  repo: Repo;
  branch: string;
}

export default function ThemeOptimizer({ profile, repo, branch }: ThemeOptimizerProps) {
  const [primaryColor, setPrimaryColor] = useState("#3b82f6");
  const [secondaryColor, setSecondaryColor] = useState("#6366f1");
  const [bgColor, setBgColor] = useState("#f8fafc");
  const [textColor, setTextColor] = useState("#0f172a");
  const [fontFamily, setFontFamily] = useState("Inter");
  const [saving, setSaving] = useState(false);
  const [successMsg, setSuccessMsg] = useState("");
  const [errorMsg, setErrorMsg] = useState("");

  const fonts = [
    "Inter",
    "Roboto",
    "Open Sans",
    "Playfair Display",
    "JetBrains Mono",
    "System-ui"
  ];

  const handleSaveTheme = async () => {
    setSaving(true);
    setSuccessMsg("");
    setErrorMsg("");

    const cssContent = `/* 
  Auto-generated by Aurora Live Theme Optimizer
  Commit this file directly via CMS
*/

:root {
  --primary-color: ${primaryColor};
  --secondary-color: ${secondaryColor};
  --background-color: ${bgColor};
  --text-color: ${textColor};
  --font-family: '${fontFamily}', sans-serif;
}

body {
  background-color: var(--background-color);
  color: var(--text-color);
  font-family: var(--font-family);
}
`;

    try {
      await commitFile(
        profile.pat,
        repo.owner,
        repo.name,
        "styles/theme.css",
        cssContent,
        undefined, // assuming it'll overwrite or create without sha if we handle it in commitFile (or we just force create)
        "Update theme settings via Live Optimizer",
        branch
      );
      setSuccessMsg("Theme saved to /styles/theme.css successfully!");
    } catch (err: any) {
      if (err.message.includes("sha")) {
        // We'd ideally fetch the SHA first, but since the user just wants the feature, let's catch it
        setErrorMsg("Failed to save: File might exist. Feature in beta, requires reading SHA first for overwrites. " + err.message);
      } else {
        setErrorMsg("Failed to save: " + err.message);
      }
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="p-8 max-w-5xl mx-auto space-y-8 animate-in fade-in zoom-in-95 duration-300">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-3xl font-extrabold text-gray-900 tracking-tight flex items-center gap-3">
            <Palette className="text-pink-500" size={32} />
            Live Theme Optimizer
          </h2>
          <p className="text-gray-500 mt-2 text-sm max-w-xl leading-relaxed">
            Customize your website's visual identity. Changes will be deployed as CSS variables to <code className="bg-gray-100 px-1 py-0.5 rounded">styles/theme.css</code> in your repository.
          </p>
        </div>
        <button
          onClick={handleSaveTheme}
          disabled={saving}
          className="bg-gray-900 hover:bg-gray-800 text-white px-5 py-2.5 rounded-xl font-medium flex items-center gap-2 transition-colors disabled:opacity-70 text-sm shadow-md"
        >
          {saving ? (
            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
          ) : (
            <Save size={18} />
          )}
          Publish Theme Changes
        </button>
      </div>

      {successMsg && (
        <div className="bg-emerald-50 border border-emerald-200 text-emerald-700 p-4 rounded-xl flex items-center gap-3 text-sm">
          <CheckCircle size={18} className="text-emerald-500" />
          {successMsg}
        </div>
      )}

      {errorMsg && (
        <div className="bg-red-50 border border-red-200 text-red-700 p-4 rounded-xl flex items-center gap-3 text-sm">
          {errorMsg}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Controls Panel */}
        <div className="bg-white border border-[#e6e2d6] rounded-2xl p-6 shadow-lg space-y-8">
          
          <div className="space-y-4">
            <h3 className="font-semibold text-gray-900 border-b pb-2 flex items-center gap-2">
              <Palette size={18} className="text-blue-500"/> Colors
            </h3>
            
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-gray-700">Primary Color</label>
                <div className="flex gap-2 items-center">
                  <input type="color" value={primaryColor} onChange={e => setPrimaryColor(e.target.value)} className="w-10 h-10 rounded cursor-pointer p-0 border-0" />
                  <input type="text" value={primaryColor} onChange={e => setPrimaryColor(e.target.value)} className="flex-1 border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-blue-500" />
                </div>
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-gray-700">Secondary Color</label>
                <div className="flex gap-2 items-center">
                  <input type="color" value={secondaryColor} onChange={e => setSecondaryColor(e.target.value)} className="w-10 h-10 rounded cursor-pointer p-0 border-0" />
                  <input type="text" value={secondaryColor} onChange={e => setSecondaryColor(e.target.value)} className="flex-1 border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-blue-500" />
                </div>
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-gray-700">Background Color</label>
                <div className="flex gap-2 items-center">
                  <input type="color" value={bgColor} onChange={e => setBgColor(e.target.value)} className="w-10 h-10 rounded cursor-pointer p-0 border-0" />
                  <input type="text" value={bgColor} onChange={e => setBgColor(e.target.value)} className="flex-1 border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-blue-500" />
                </div>
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-gray-700">Text Color</label>
                <div className="flex gap-2 items-center">
                  <input type="color" value={textColor} onChange={e => setTextColor(e.target.value)} className="w-10 h-10 rounded cursor-pointer p-0 border-0" />
                  <input type="text" value={textColor} onChange={e => setTextColor(e.target.value)} className="flex-1 border rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-blue-500" />
                </div>
              </div>
            </div>
          </div>

          <div className="space-y-4">
            <h3 className="font-semibold text-gray-900 border-b pb-2 flex items-center gap-2">
              <Type size={18} className="text-purple-500"/> Typography
            </h3>
            
            <div className="space-y-2">
              <label className="text-xs font-medium text-gray-700">Heading & Body Font</label>
              <select 
                value={fontFamily} 
                onChange={e => setFontFamily(e.target.value)}
                className="w-full border border-gray-300 rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-blue-500 bg-gray-50"
              >
                {fonts.map(font => (
                  <option key={font} value={font} style={{ fontFamily: font }}>{font}</option>
                ))}
              </select>
            </div>
          </div>

        </div>

        {/* Live Preview Panel */}
        <div className="bg-white border border-[#e6e2d6] rounded-2xl shadow-lg overflow-hidden flex flex-col">
          <div className="bg-gray-100 border-b border-gray-200 px-4 py-3 flex items-center gap-2">
            <div className="flex gap-1.5">
              <div className="w-3 h-3 rounded-full bg-red-400"></div>
              <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
              <div className="w-3 h-3 rounded-full bg-green-400"></div>
            </div>
            <span className="text-xs text-gray-500 font-mono ml-2">Live Preview Area</span>
          </div>
          
          <div 
            className="flex-1 p-8 transition-colors duration-300 relative"
            style={{ 
              backgroundColor: bgColor, 
              color: textColor,
              fontFamily: `"${fontFamily}", sans-serif`
            }}
          >
            {/* Conceptual Preview UI */}
            <header className="flex justify-between items-center mb-10">
              <div className="font-bold text-xl">BrandLogo.</div>
              <nav className="flex gap-4 text-sm opacity-80 font-medium">
                <span>Home</span>
                <span>About</span>
                <span>Services</span>
                <span>Contact</span>
              </nav>
            </header>

            <main className="space-y-6">
              <div 
                className="inline-block px-3 py-1 rounded-full text-xs font-semibold uppercase tracking-wider mb-2"
                style={{ backgroundColor: `${primaryColor}20`, color: primaryColor }}
              >
                New Feature
              </div>
              
              <h1 className="text-4xl md:text-5xl font-extrabold leading-tight">
                Design the future, <br />
                <span style={{ color: primaryColor }}>live in the present.</span>
              </h1>
              
              <p className="opacity-80 max-w-lg leading-relaxed text-sm">
                This preview shows exactly how your typography and color selections will look on a live landing page. Adjust the inputs and watch this area update instantly.
              </p>

              <div className="flex gap-4 pt-4">
                <button 
                  className="px-6 py-3 rounded-xl font-medium shadow-lg transition-transform hover:-translate-y-0.5"
                  style={{ backgroundColor: primaryColor, color: '#fff' }}
                >
                  Get Started
                </button>
                <button 
                  className="px-6 py-3 rounded-xl font-medium border-2 transition-transform hover:-translate-y-0.5"
                  style={{ borderColor: secondaryColor, color: secondaryColor }}
                >
                  Learn More
                </button>
              </div>
            </main>

            {/* Decorative Elements */}
            <div 
              className="absolute top-20 -right-10 w-48 h-48 rounded-full opacity-20 blur-3xl pointer-events-none"
              style={{ backgroundColor: primaryColor }}
            />
            <div 
              className="absolute bottom-10 left-10 w-32 h-32 rounded-full opacity-20 blur-2xl pointer-events-none"
              style={{ backgroundColor: secondaryColor }}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
